# Generated by Django 5.2.4 on 2025-07-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='tags',
            field=models.CharField(db_index=True, help_text='Taguri separate prin virgulă. Ex: plajă, istorie, natură', max_length=255),
        ),
    ]
