# Generated by Django 5.1.4 on 2026-03-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_add_recommendation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='status',
        ),
    ]
