# Generated by Django 5.2.4 on 2026-03-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_add_recommendation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='status',
        ),
    ]
