# Generated by Django 5.2.4 on 2026-03-07 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_location_climate'),
        ('recommendations', '0007_recommendation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='accommodation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='attractions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='restaurants',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='tags',
            field=models.CharField(blank=True, db_index=True, help_text='Taguri separate prin virgulă. Ex: plajă, istorie, natură', max_length=255),
        ),
    ]
