# Generated by Django 5.2.4 on 2025-09-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
