# Generated by Django 5.2.4 on 2025-07-19 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_season', models.CharField(choices=[('spring', 'Primăvară'), ('summer', 'Vara'), ('autumn', 'Toamnă'), ('winter', 'Iarna'), ('any', 'Oricare')], default='any', max_length=20)),
                ('interests', models.TextField(help_text='Interese separate prin virgulă. Ex: plajă, munte, cultură')),
                ('travel_start', models.DateField(blank=True, null=True)),
                ('travel_end', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
