# Generated by Django 5.2.4 on 2025-07-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accommodation_preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='restaurant_preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
