# Generated by Django 5.2.4 on 2025-07-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_accommodation_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_climate',
            field=models.CharField(blank=True, choices=[('tropical', 'Tropical'), ('temperate', 'Temperate'), ('arctic', 'Arctic')], max_length=50, null=True),
        ),
    ]
