# Generated by Django 5.2.4 on 2025-07-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0003_userprofile_preferred_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_locations',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='locations.location'),
        ),
    ]
