# Generated by Django 5.2.4 on 2025-07-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('climate', models.CharField(choices=[('tropical', 'Tropical'), ('temperate', 'Temperate'), ('arid', 'Arid'), ('polar', 'Polar')], max_length=50)),
                ('interest_type', models.CharField(choices=[('adventure', 'Adventure'), ('cultural', 'Cultural'), ('relaxation', 'Relaxation'), ('nature', 'Nature')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_activities', to='locations.location')),
            ],
        ),
    ]
