# Generated by Django 5.2.4 on 2025-07-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_location'),
        ('locations', '0002_remove_location_activities_alter_location_climate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_set', to='locations.location'),
        ),
    ]
