# Generated by Django 5.2.4 on 2025-07-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_activity_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location',
        ),
    ]
