# Generated by Django 5.2.4 on 2025-07-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_activity_location'),
        ('locations', '0005_remove_location_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_set', to='locations.location'),
            preserve_default=False,
        ),
    ]
