# Generated by Django 5.2.4 on 2025-07-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_activity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
