# Generated by Django 5.2.4 on 2025-07-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_location'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='activities',
        ),
        migrations.AlterField(
            model_name='location',
            name='climate',
            field=models.CharField(choices=[('Temperat', 'Temperat'), ('Tropical', 'Tropical'), ('Arid', 'Arid'), ('Rece', 'Rece'), ('Mediteranean', 'Mediteranean')], default=(('Temperat', 'Temperat'),), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='locations', to='activities.activity'),
        ),
    ]
