# Generated by Django 5.2.4 on 2025-07-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_activity_location'),
        ('locations', '0002_remove_location_activities_alter_location_climate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='activities',
            field=models.ManyToManyField(related_name='locations', to='activities.activity'),
        ),
    ]
