# Generated by Django 5.2.4 on 2025-07-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_remove_activity_location'),
        ('locations', '0003_alter_location_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='locations', to='activities.activity'),
        ),
    ]
