# Generated by Django 5.2.4 on 2025-07-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='activities',
        ),
    ]
