# Generated by Django 5.2.4 on 2025-07-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_location_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='climate',
            field=models.CharField(choices=[('', 'Orice climă'), ('tropical', 'Tropical'), ('temperate', 'Temperat'), ('arid', 'Arid'), ('polar', 'Polar'), ('rece', 'Rece')], max_length=50),
        ),
    ]
